-- LLM usage tracking — costs per API call
CREATE TABLE IF NOT EXISTS llm_usage (
    id SERIAL PRIMARY KEY,
    service VARCHAR(50) NOT NULL,        -- 'summary', 'guardian', 'kleshnya', etc.
    model VARCHAR(100) NOT NULL,
    prompt_tokens INT NOT NULL DEFAULT 0,
    completion_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    cost_usd NUMERIC(10, 6) NOT NULL DEFAULT 0,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_llm_usage_service ON llm_usage(service);
CREATE INDEX IF NOT EXISTS idx_llm_usage_created ON llm_usage(created_at);

-- Chat summaries generated by sub-agent
CREATE TABLE IF NOT EXISTS chat_summaries (
    id SERIAL PRIMARY KEY,
    channel_id INT,
    summary TEXT NOT NULL,
    messages_count INT NOT NULL DEFAULT 0,
    period_from TIMESTAMPTZ,
    period_to TIMESTAMPTZ,
    model VARCHAR(100),
    tokens_used INT DEFAULT 0,
    cost_usd NUMERIC(10, 6) DEFAULT 0,
    requested_by INT REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
