const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');

function read(relPath) {
    return fs.readFileSync(path.join(ROOT, relPath), 'utf8');
}

test('products compatibility page keeps business-aware products IA with restored product menu entrypoints', () => {
    const html = read('programs.html');
    const sidebar = read('js/components/sidebar.js');

    assert.match(html, /Products · Продукти Парку Закревського/);
    assert.doesNotMatch(html, /id="productsBusinessSelect"/);
    assert.doesNotMatch(html, /business-context-selector/);
    assert.match(html, /Майстерня долі/);
    assert.match(html, /id="maysternyaPanel"/);
    assert.match(html, /id="maysternyaProductsGrid"/);
    assert.match(html, /Демо консультація/);
    assert.match(html, /Повна консультація/);
    assert.match(html, /id="productIaTabs"/);
    assert.match(html, /id="catalogsPanel"/);
    assert.match(html, /id="catalogsGrid"/);
    assert.match(html, /id="kitchenPanel"/);
    assert.match(html, /id="kitchenSubtabs"/);
    assert.match(html, /id="menuSectionFilter"/);
    assert.match(html, /id="kitchenGrid"/);
    assert.match(html, /id="pf-menu-section"/);
    assert.match(html, /id="pf-weight-value"/);
    assert.match(html, /id="pf-serving-unit"/);
    assert.match(html, /id="pf-price-variant-note"/);
    assert.match(html, /id="pf-availability-status"/);
    assert.match(html, /id="pf-allergens"/);
    assert.match(html, /id="productAiAutofillBtn"/);
    assert.match(html, /id="productAiReviewModal"/);
    assert.match(html, /js\/kitchen-menu-images\.js/);
    assert.match(html, /css\/pages-products\.css/);
    assert.match(html, /Холодні закуски/);
    assert.match(html, /Коктейлі та холодні напої/);
    assert.match(html, /id="productDocumentModal"/);
    assert.match(html, /Картку перевірено вручну/);
    assert.match(html, /Картка відповідає документу/);
    assert.match(html, /product-doc-modal-card/);
    assert.match(html, /id="productDocFeedback"/);
    assert.match(html, /id="productDocCloseBtn"/);
    assert.match(html, /id="productDocUrlError"/);
    assert.match(html, /product-doc-check-card/);
    assert.match(sidebar, /href: '\/programs'/);
    assert.match(sidebar, /href: '\/programs#animation'/);
    assert.match(sidebar, /href: '\/programs#kitchen-cakes'/);
    assert.match(sidebar, /href: '\/programs#kitchen-menu'/);
    assert.match(sidebar, /href: '\/programs#catalogs'/);
});

test('products frontend wires document linkage and catalog entry points', () => {
    const pageJs = read('js/programs-page.js');
    const apiJs = read('js/api.js');

    assert.match(pageJs, /apiUpdateProductDocument/);
    assert.match(pageJs, /apiGetProductCatalogs/);
    assert.match(pageJs, /renderKitchenSubtabs/);
    assert.match(pageJs, /initProductBusinessContext/);
    assert.match(pageJs, /applyProductBusinessContext/);
    assert.match(pageJs, /setProductBusinessContext/);
    assert.match(pageJs, /PRODUCT_CATEGORY_HASH_TO_ID/);
    assert.match(pageJs, /readInitialCategory/);
    assert.match(pageJs, /'#animation': 'animation'/);
    assert.match(pageJs, /'#kitchen-cakes'/);
    assert.match(pageJs, /'#kitchen-menu'/);
    assert.match(pageJs, /currentCategory = readInitialCategory\(\)/);
    assert.match(pageJs, /getProductApiBusinessContext/);
    assert.match(pageJs, /businessContext: getProductApiBusinessContext\(\)/);
    assert.match(pageJs, /renderMaysternyaProducts/);
    assert.doesNotMatch(pageJs, /PRODUCT_BUSINESS_STORAGE_KEY/);
    assert.match(pageJs, /renderKitchenProducts/);
    assert.match(pageJs, /renderMenuSectionFilter/);
    assert.match(pageJs, /MENU_SECTION_ORDER/);
    assert.match(pageJs, /getMenuCompleteness/);
    assert.match(pageJs, /menuSection/);
    assert.match(pageJs, /weightValue/);
    assert.match(pageJs, /priceVariantNote/);
    assert.match(pageJs, /availabilityStatus/);
    assert.match(pageJs, /cakeDecoration/);
    assert.match(pageJs, /allergens/);
    assert.match(pageJs, /MENU_AI_BLOCKS/);
    assert.match(pageJs, /openMenuAiReviewWizard/);
    assert.match(pageJs, /function productMenuImageManifestUrl/);
    assert.match(pageJs, /window\.KITCHEN_MENU_IMAGES/);
    assert.match(pageJs, /function renderKitchenCardVisual/);
    assert.match(pageJs, /function renderKitchenMenuAiActions/);
    assert.match(pageJs, /function renderKitchenMenuImageStudio/);
    assert.match(pageJs, /function renderKitchenMenuImagePreview/);
    assert.match(pageJs, /function menuImageDraftStatusLabel/);
    assert.match(pageJs, /function generateKitchenMenuImage/);
    assert.match(pageJs, /function applyKitchenMenuImageDraft/);
    assert.match(pageJs, /function rejectKitchenMenuImageDraft/);
    assert.match(pageJs, /function saveKitchenMenuImageDraft/);
    assert.match(pageJs, /data-menu-image-action="apply"/);
    assert.match(pageJs, /data-menu-image-action="reject"/);
    assert.match(pageJs, /imageStudio/);
    assert.match(pageJs, /buildKitchenMenuImagePrompt/);
    assert.match(pageJs, /apiGenerateProductMenuImage/);
    assert.match(pageJs, /apiApplyProductMenuImage/);
    assert.match(pageJs, /apiRejectProductMenuImage/);
    assert.match(pageJs, /applyMenuAiReviewFinal/);
    assert.match(pageJs, /techCard/);
    assert.match(pageJs, /ingredients/);
    assert.match(pageJs, /sourceDocumentVerifiedManual/);
    assert.match(pageJs, /sourceCardMatchesDocument/);
    assert.match(pageJs, /openProductDocumentModal/);
    assert.match(pageJs, /validateProductDocumentPayload/);
    assert.match(pageJs, /setProductDocumentSaving/);
    assert.match(pageJs, /normalizeProductDocumentError/);
    assert.match(pageJs, /productDocumentSaving/);
    assert.match(pageJs, /Щоб закрити без змін/);
    assert.match(pageJs, /confirmModal\('Відвʼязати документ від цієї картки продукту\?'/);
    assert.match(apiJs, /apiGetProductCatalogs/);
    assert.match(apiJs, /apiUpdateProductDocument/);
    assert.match(apiJs, /addProductBusinessContextParam/);
    assert.match(apiJs, /CRM_BUSINESS_SCOPED_PAGES/);
    assert.match(apiJs, /function getCrmBusinessState/);
    assert.match(apiJs, /state: getCrmBusinessState/);
    assert.match(apiJs, /crmBusinessContextChanged/);
    assert.match(apiJs, /businessContext/);
    assert.match(apiJs, /\/products\/catalogs/);
    assert.match(apiJs, /\/source-document/);
});

test('products API reuses existing catalog engine and validates source documents', () => {
    const productsRoute = read('routes/products.js');
    const menuPhotoService = read('services/menuPhotoGeneration.js');
    const migration = read('db/migrations/191_products_source_document_linkage.sql');
    const kitchenMigration = read('db/migrations/199_products_kitchen_fields.sql');
    const menuMigration = read('db/migrations/200_products_menu_structure_fields.sql');
    const businessMigration = read('db/migrations/209_products_business_context_scope.sql');

    assert.match(productsRoute, /router\.get\('\/catalogs'/);
    assert.match(productsRoute, /businessContextFromRequest/);
    assert.match(productsRoute, /pushBusinessContextCondition/);
    assert.match(productsRoute, /businessContext: row\.business_context/);
    assert.match(productsRoute, /INSERT INTO products \(id, business_context/);
    assert.match(productsRoute, /FROM catalog_definitions cd/);
    assert.match(productsRoute, /href: row\.id === 'graduation' \? '\/designs#catalog-graduation'/);
    assert.match(productsRoute, /secondaryHref: row\.id === 'graduation' \? null : '\/designs#catalogs'/);
    assert.match(productsRoute, /router\.patch\('\/:id\/source-document'/);
    assert.match(productsRoute, /SOURCE_DOCUMENT_KINDS/);
    assert.match(productsRoute, /source_document_kind must be google_doc, pdf, or link/);
    assert.match(migration, /source_document_url/);
    assert.match(migration, /source_document_verified_manual/);
    assert.match(migration, /source_card_matches_document/);
    assert.match(migration, /google_doc/);
    assert.match(migration, /pdf/);
    assert.match(migration, /link/);
    assert.match(productsRoute, /normalizeProductPayload/);
    assert.match(productsRoute, /kitchenType/);
    assert.match(productsRoute, /shortDescription/);
    assert.match(productsRoute, /techCard/);
    assert.match(productsRoute, /PRODUCT_AVAILABILITY_STATUSES/);
    assert.match(productsRoute, /menuSection/);
    assert.match(productsRoute, /servingUnit/);
    assert.match(productsRoute, /weightValue/);
    assert.match(productsRoute, /priceVariantNote/);
    assert.match(productsRoute, /availabilityStatus/);
    assert.match(productsRoute, /allergens/);
    assert.match(productsRoute, /ai_card_draft/);
    assert.match(productsRoute, /normalizeMenuImageStudio/);
    assert.match(productsRoute, /MENU_IMAGE_STUDIO_SIZES/);
    assert.match(productsRoute, /router\.post\('\/menu-ai-draft'/);
    assert.match(productsRoute, /router\.post\('\/:id\/menu-image\/draft'/);
    assert.match(productsRoute, /router\.post\('\/:id\/menu-image\/generate'[\s\S]+handleMenuImageDraftRequest/);
    assert.match(productsRoute, /router\.post\('\/:id\/menu-image\/apply'/);
    assert.match(productsRoute, /router\.post\('\/:id\/menu-image\/reject'/);
    assert.match(productsRoute, /router\.get\('\/:id\/menu-image\/status'/);
    assert.match(menuPhotoService, /OPENAI_MENU_IMAGE_MODEL/);
    assert.match(menuPhotoService, /\/images\/generations/);
    assert.match(kitchenMigration, /domain VARCHAR\(30\)/);
    assert.match(kitchenMigration, /kitchen_type VARCHAR\(30\)/);
    assert.match(kitchenMigration, /cake_decoration TEXT/);
    assert.match(menuMigration, /menu_section VARCHAR\(120\)/);
    assert.match(menuMigration, /serving_unit VARCHAR\(60\)/);
    assert.match(menuMigration, /weight_value VARCHAR\(120\)/);
    assert.match(menuMigration, /price_variant_note TEXT/);
    assert.match(menuMigration, /availability_status VARCHAR\(30\)/);
    assert.match(menuMigration, /products_availability_status_check/);
    assert.match(businessMigration, /business_context VARCHAR\(64\)/);
    assert.match(businessMigration, /idx_products_business_domain_category/);
    assert.match(businessMigration, /maysternya_doli/);
    assert.match(businessMigration, /Повна консультація\(90\)/);
});

test('products lifecycle uses active working lists, duplicate guards, and soft-deactivation cleanup', () => {
    const pageJs = read('js/programs-page.js');
    const productsRoute = read('routes/products.js');
    const cleanupMigration = read('db/migrations/224_products_zagadky_shi_duplicate_cleanup.sql');
    const cleanupMarkers = [...cleanupMigration.matchAll(/'migration_[^']+'/g)].map(match => match[0].slice(1, -1));

    assert.match(pageJs, /apiGetProducts\(true, \{ businessContext: getProductApiBusinessContext\(\) \}\)/);
    assert.match(pageJs, /productSaveInFlight/);
    assert.match(pageJs, /productDeleteInFlight/);
    assert.match(pageJs, /findActiveProductDuplicateInState/);
    assert.match(pageJs, /duplicateProductMessage/);
    assert.doesNotMatch(pageJs, />Видалити<\/button>/);

    assert.match(productsRoute, /PRODUCT_MUTATION_ROLES/);
    assert.match(productsRoute, /pg_advisory_xact_lock\(hashtext\(\$1\)\)/);
    assert.match(productsRoute, /PRODUCT_DUPLICATE_ACTIVE_SCOPE/);
    assert.match(productsRoute, /router\.delete\('\/:id', requireRole\(\.\.\.PRODUCT_MUTATION_ROLES\)/);
    assert.match(productsRoute, /availability_status = 'hidden'/);
    assert.doesNotMatch(productsRoute, /express-rate-limit/);
    assert.match(productsRoute, /createWriteRateLimiter\('product-menu-ai-draft'/);
    assert.match(productsRoute, /createWriteRateLimiter\('product-menu-image-generation'/);
    assert.match(productsRoute, /loadMenuAiWarehouseItems\(pool, businessContext\)/);
    assert.match(productsRoute, /COALESCE\(ws\.business_context, '\$\{DEFAULT_BUSINESS_CONTEXT\}'\) = \$2/);
    assert.match(productsRoute, /INSERT INTO warehouse_history \(stock_id, change, reason, created_by, business_context\)/);
    assert.match(productsRoute, /warehouse_stock_movements \([\s\S]*business_context/);

    assert.match(cleanupMigration, /MIGRATION_KIND: mixed/);
    assert.match(cleanupMigration, /Загадки ШІ/);
    assert.match(cleanupMigration, /tmp_products_zagadky_shi_duplicates/);
    assert.match(cleanupMigration, /UPDATE bookings b[\s\S]*program_id = t\.canonical_id/);
    assert.match(cleanupMigration, /UPDATE leads l[\s\S]*program_id = t\.canonical_id/);
    assert.match(cleanupMigration, /UPDATE automation_rules ar[\s\S]*trigger_condition = rr\.trigger_condition/);
    assert.match(cleanupMigration, /product_code = LEFT\(COALESCE\(NULLIF\(bt\.product_code, ''\), p\.code\), 50\)/);
    assert.match(cleanupMigration, /CREATE INDEX IF NOT EXISTS idx_products_active_scope_name_key/);
    assert.ok(cleanupMarkers.length > 0, 'cleanup migration should keep an operator marker');
    assert.ok(cleanupMarkers.every(marker => marker.length <= 50), 'cleanup migration updated_by markers must fit VARCHAR(50)');
});

test('catalog image jobs encode Kie task ids consistently', () => {
    const catalogsRoute = read('routes/catalogs.js');
    const scheduler = read('services/scheduler.js');

    assert.match(catalogsRoute, /function getKieJobRecord\(taskId\)/);
    assert.match(catalogsRoute, /encodeURIComponent\(normalizedTaskId\)/);
    assert.match(catalogsRoute, /router\.get\('\/generate-image\/:taskId', requireRole/);
    assert.doesNotMatch(catalogsRoute, /recordInfo\?taskId=\$\{taskId\}/);
    assert.doesNotMatch(catalogsRoute, /recordInfo\?taskId=\$\{normalizedTaskId\}/);
    assert.match(scheduler, /recordInfo\?taskId=\$\{encodeURIComponent\(taskData\.data\.taskId\)\}/);
});

test('design catalog deep links remain backed by the existing designs viewer', () => {
    const designsJs = read('js/designs-page.js');

    assert.match(designsJs, /openCatalogHash/);
    assert.match(designsJs, /catalog-/);
    assert.match(designsJs, /catalogId === 'graduation'/);
    assert.match(designsJs, /openCatalog\('graduation'\)/);
    assert.match(designsJs, /openCatalogPages\(catalogId\)/);
});
