export const BOOKING_STATUS = {
  DRAFT: 'DRAFT',
  HOLD: 'HOLD',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  REFUNDED: 'REFUNDED',
} as const;

export type BookingStatusType = (typeof BOOKING_STATUS)[keyof typeof BOOKING_STATUS];

export const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  SOLD_OUT: 'SOLD_OUT',
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED',
} as const;

export type EventStatusType = (typeof EVENT_STATUS)[keyof typeof EVENT_STATUS];

export const MANAGER_ROLE = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
} as const;

export type ManagerRoleType = (typeof MANAGER_ROLE)[keyof typeof MANAGER_ROLE];

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;

export type PaymentStatusType = (typeof PAYMENT_STATUS)[keyof typeof PAYMENT_STATUS];

export const NOTIFICATION_STATUS = {
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RETRY: 'RETRY',
} as const;

export type NotificationStatusType =
  (typeof NOTIFICATION_STATUS)[keyof typeof NOTIFICATION_STATUS];

export const API_ERROR_CODE = {
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_PHONE_FORMAT: 'INVALID_PHONE_FORMAT',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_PUBLISHED: 'EVENT_NOT_PUBLISHED',
  EVENT_CAPACITY_FULL: 'EVENT_CAPACITY_FULL',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CAPACITY_EXCEEDED: 'BOOKING_CAPACITY_EXCEEDED',
  BOOKING_HOLD_EXPIRED: 'BOOKING_HOLD_EXPIRED',
  BOOKING_INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PROMO_CODE_INVALID: 'PROMO_CODE_INVALID',
  PROMO_CODE_EXPIRED: 'PROMO_CODE_EXPIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ApiErrorCodeType = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];

export const STATUS_EMOJI: Record<string, string> = {
  DRAFT: '📝',
  HOLD: '⏳',
  PENDING_PAYMENT: '💳',
  CONFIRMED: '✅',
  PAID: '💚',
  COMPLETED: '🏁',
  CANCELLED: '❌',
  NO_SHOW: '👻',
  REFUNDED: '💸',
};
