const INIT_DATABASE_FLOW = {
    serverFile: 'server.js',
    steps: ['initDatabase', 'runMigrations', 'initDatabase'],
    reason: 'Schema-fenced legacy two-phase startup keeps old environments bootable while SQL migrations remain the durable schema history.'
};

const STARTUP_SCHEMA_TABLES = [
    'afisha',
    'afisha_templates',
    'automation_rules',
    'banquet_group_bookings',
    'banquet_groups',
    'booking_counter',
    'bookings',
    'budget_plans',
    'certificate_counter',
    'certificates',
    'contractor_notifications',
    'contractors',
    'customers',
    'design_collections',
    'design_tags',
    'designs',
    'finance_categories',
    'finance_transactions',
    'history',
    'kleshnya_chat',
    'kleshnya_messages',
    'lines_by_date',
    'pending_animators',
    'point_transactions',
    'profile_avatar_blobs',
    'procurement_items',
    'procurement_lists',
    'products',
    'schema_migrations',
    'scheduled_deletions',
    'settings',
    'staff',
    'staff_schedule',
    'task_logs',
    'task_templates',
    'tasks',
    'telegram_known_chats',
    'telegram_known_threads',
    'user_action_log',
    'user_points',
    'user_streaks',
    'users'
];

const STARTUP_SCHEMA_COLUMNS = [
    'afisha.description',
    'afisha.line_id',
    'afisha.original_time',
    'afisha.template_id',
    'afisha.type',
    'bookings.banquet_adults',
    'bookings.costume',
    'bookings.customer_id',
    'bookings.extra_data',
    'bookings.group_name',
    'bookings.kids_count',
    'bookings.payment_method',
    'bookings.skip_notification',
    'bookings.status',
    'bookings.telegram_message_id',
    'bookings.updated_at',
    'certificates.customer_id',
    'certificates.season',
    'certificates.value_uah',
    'customer_cards.business_context',
    'customers.business_context',
    'leads.business_context',
    'mailing_list.business_context',
    'products.business_context',
    'staff.rate_unit',
    'staff.telegram_username',
    'task_templates.business_context',
    'task_templates.category',
    'tasks.afisha_id',
    'tasks.archive_reason',
    'tasks.archived_at',
    'tasks.business_context',
    'tasks.category',
    'tasks.control_policy',
    'tasks.deadline',
    'tasks.dependency_ids',
    'tasks.duplicate_of_task_id',
    'tasks.escalation_level',
    'tasks.last_reminded_at',
    'tasks.owner',
    'tasks.source_id',
    'tasks.source_type',
    'tasks.task_type',
    'tasks.template_id',
    'tasks.time_window_end',
    'tasks.time_window_start',
    'tasks.type',
    'tasks.version',
    'users.action_allowlist',
    'users.action_denylist',
    'users.telegram_chat_id',
    'users.telegram_username'
];

const STARTUP_SCHEMA_INDEXES = [
    'idx_afisha_date',
    'idx_banquet_group_bookings_booking',
    'idx_banquet_group_bookings_group',
    'idx_banquet_groups_business_date',
    'idx_banquet_groups_primary_booking',
    'idx_bookings_customer_id',
    'idx_bookings_date',
    'idx_bookings_date_status',
    'idx_bookings_line_date',
    'idx_bookings_linked_to',
    'idx_bookings_program_id',
    'idx_budget_plans_year_month',
    'idx_certificates_cert_code',
    'idx_certificates_customer_id',
    'idx_certificates_status',
    'idx_certificates_valid_until',
    'idx_contractor_notif_contractor',
    'idx_contractor_notif_status',
    'idx_contractors_active',
    'idx_contractors_invite',
    'idx_customers_child_name',
    'idx_customers_business_phone',
    'idx_customers_instagram',
    'idx_customers_name',
    'idx_customers_phone',
    'idx_design_tags_tag',
    'idx_designs_collection',
    'idx_designs_pinned',
    'idx_designs_publish_date',
    'idx_finance_categories_type',
    'idx_finance_transactions_booking',
    'idx_finance_transactions_category',
    'idx_finance_transactions_date',
    'idx_finance_transactions_type',
    'idx_history_action',
    'idx_history_created_at',
    'idx_leads_business_status_created',
    'idx_kleshnya_chat_username',
    'idx_kleshnya_messages_expires',
    'idx_kleshnya_messages_scope',
    'idx_lines_by_date_date',
    'idx_lines_by_date_line_date',
    'idx_point_transactions_username',
    'idx_profile_avatar_blobs_created_at_desc',
    'idx_profile_avatar_blobs_username',
    'idx_procurement_items_list',
    'idx_procurement_items_stock',
    'idx_procurement_lists_department',
    'idx_procurement_lists_status',
    'idx_products_active',
    'idx_products_availability_status',
    'idx_products_business_active',
    'idx_products_business_code',
    'idx_products_business_domain_category',
    'idx_products_category',
    'idx_products_domain',
    'idx_products_kitchen_type',
    'idx_products_menu_section',
    'idx_scheduled_deletions_delete_at',
    'idx_staff_active',
    'idx_staff_department',
    'idx_staff_schedule_date',
    'idx_staff_schedule_staff',
    'idx_task_logs_created_at',
    'idx_task_logs_task_id',
    'idx_task_templates_business_active_created',
    'idx_tasks_afisha_id',
    'idx_tasks_business_completed_at',
    'idx_tasks_business_owner_active',
    'idx_tasks_business_source',
    'idx_tasks_business_status_date',
    'idx_tasks_category',
    'idx_tasks_completed_at',
    'idx_tasks_created_by',
    'idx_tasks_date',
    'idx_tasks_deadline',
    'idx_tasks_duplicate_of_task_id',
    'idx_tasks_escalation',
    'idx_tasks_owner',
    'idx_tasks_status',
    'idx_tasks_task_type',
    'idx_tasks_template_id',
    'idx_tasks_type',
    'idx_user_action_log_created_at',
    'idx_user_action_log_username',
    'idx_user_points_username',
    'idx_users_action_allowlist_gin',
    'idx_users_action_denylist_gin',
    'idx_users_is_active',
    'idx_users_role'
];

const STARTUP_SCHEMA_FUNCTIONS = ['update_updated_at_column'];
const STARTUP_SCHEMA_TRIGGERS = ['trg_bookings_updated_at'];

const STARTUP_DATA_BOOTSTRAPS = [
    { name: 'firstUserBootstrap', sourceFile: 'db/index.js', marker: 'ensureInitialLoginUser()', owner: 'auth', mode: 'env-gated' },
    { name: 'legacyUserResetMarker', sourceFile: 'db/index.js', marker: '007_upsert_users_v12_5', owner: 'auth', mode: 'mark-only' },
    { name: 'legacyAnnaArtemMarker', sourceFile: 'db/index.js', marker: '008_add_anna_artem', owner: 'auth', mode: 'mark-only' },
    { name: 'productsSeed', sourceFile: 'db/index.js', marker: 'seedProducts()', owner: 'products', mode: 'seed-if-empty' },
    { name: 'staffAndScheduleSeed', sourceFile: 'db/index.js', marker: 'seedStaff()', owner: 'staff', mode: 'seed-if-empty' },
    { name: 'automationRulesSeed', sourceFile: 'db/index.js', marker: 'Automation rules seeded', owner: 'automation', mode: 'seed-if-empty' },
    { name: 'contractorZhenyaSeed', sourceFile: 'db/index.js', marker: '008_seed_contractor_zhenya', owner: 'contractors', mode: 'legacy-seed-marker' },
    { name: 'openclawUserBootstrap', sourceFile: 'db/index.js', marker: '009_seed_user_openclaw', owner: 'openclaw', mode: 'env-gated-marker' },
    { name: 'financeCategoriesSeed', sourceFile: 'db/index.js', marker: 'Finance categories seeded', owner: 'finance', mode: 'seed-if-empty' },
    { name: 'greetingCacheStartupDelete', sourceFile: 'server.js', marker: "DELETE FROM kleshnya_messages WHERE scope = 'daily_greeting'", owner: 'kleshnya', mode: 'startup-data-delete' }
];

const DB_STARTUP_SURFACE_DOC = 'docs/DB_STARTUP_SURFACE.md';
const STARTUP_DATA_BOOTSTRAP_MODES = [
    'env-gated',
    'mark-only',
    'seed-if-empty',
    'legacy-seed-marker',
    'env-gated-marker',
    'startup-data-delete'
];

module.exports = {
    INIT_DATABASE_FLOW,
    STARTUP_SCHEMA_TABLES,
    STARTUP_SCHEMA_COLUMNS,
    STARTUP_SCHEMA_INDEXES,
    STARTUP_SCHEMA_FUNCTIONS,
    STARTUP_SCHEMA_TRIGGERS,
    STARTUP_DATA_BOOTSTRAPS,
    STARTUP_DATA_BOOTSTRAP_MODES,
    DB_STARTUP_SURFACE_DOC
};
