$ErrorActionPreference='Stop'
Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class EgFocus{[DllImport("user32.dll")]public static extern bool SetProcessDPIAware();[DllImport("user32.dll")]public static extern bool ShowWindow(IntPtr h,int n);[DllImport("user32.dll")]public static extern bool MoveWindow(IntPtr h,int x,int y,int w,int height,bool repaint);[DllImport("user32.dll")]public static extern int GetSystemMetrics(int n);[DllImport("user32.dll")]public static extern bool SetForegroundWindow(IntPtr h);[DllImport("user32.dll")]public static extern bool BringWindowToTop(IntPtr h);[DllImport("user32.dll")]public static extern IntPtr GetForegroundWindow();[DllImport("user32.dll")]public static extern uint GetWindowThreadProcessId(IntPtr h,IntPtr p);[DllImport("kernel32.dll")]public static extern uint GetCurrentThreadId();[DllImport("user32.dll")]public static extern bool AttachThreadInput(uint a,uint b,bool attach);public static bool Force(IntPtr h){var current=GetCurrentThreadId();var foreground=GetWindowThreadProcessId(GetForegroundWindow(),IntPtr.Zero);var attached=foreground!=0&&foreground!=current&&AttachThreadInput(current,foreground,true);try{ShowWindow(h,9);MoveWindow(h,0,0,GetSystemMetrics(0),Math.Max(600,GetSystemMetrics(1)-80),true);BringWindowToTop(h);return SetForegroundWindow(h)&&GetForegroundWindow()==h;}finally{if(attached)AttachThreadInput(current,foreground,false);}}}'
[void][EgFocus]::SetProcessDPIAware()
$t=@(Get-Process Viber -ErrorAction SilentlyContinue|Where-Object{$_.MainWindowHandle-ne 0})
if($t.Count-ne 1){@{status='target_not_unique'}|ConvertTo-Json -Compress;exit 2}
[void][EgFocus]::ShowWindow($t[0].MainWindowHandle,9);[void][EgFocus]::MoveWindow($t[0].MainWindowHandle,0,0,[EgFocus]::GetSystemMetrics(0),([Math]::Max(600,[EgFocus]::GetSystemMetrics(1)-80)),$true);[void][EgFocus]::SetForegroundWindow($t[0].MainWindowHandle)
if([EgFocus]::GetForegroundWindow()-ne $t[0].MainWindowHandle){Add-Type -AssemblyName Microsoft.VisualBasic;[void][Microsoft.VisualBasic.Interaction]::AppActivate($t[0].Id)}
if([EgFocus]::GetForegroundWindow()-ne $t[0].MainWindowHandle){[void][EgFocus]::Force($t[0].MainWindowHandle)}
Start-Sleep -Milliseconds 500
@{status=$(if([EgFocus]::GetForegroundWindow()-eq $t[0].MainWindowHandle){'focused'}else{'focus_failed'})}|ConvertTo-Json -Compress
